package com.cheersson.qrcode.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.code
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.rule
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private String rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.available
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.code
     *
     * @return the value of category.code
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.code
     *
     * @param code the value for category.code
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.rule
     *
     * @return the value of category.rule
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.rule
     *
     * @param rule the value for category.rule
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.available
     *
     * @return the value of category.available
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.available
     *
     * @param available the value for category.available
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}