package com.cheersson.qrcode.model;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.categoryId
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.code
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.customerCode
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long customercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.customerName
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Long customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.version
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.remark
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.available
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.categoryId
     *
     * @return the value of item.categoryId
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.categoryId
     *
     * @param categoryid the value for item.categoryId
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.code
     *
     * @return the value of item.code
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.code
     *
     * @param code the value for item.code
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setCode(Long code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setName(Long name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.customerCode
     *
     * @return the value of item.customerCode
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getCustomercode() {
        return customercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.customerCode
     *
     * @param customercode the value for item.customerCode
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setCustomercode(Long customercode) {
        this.customercode = customercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.customerName
     *
     * @return the value of item.customerName
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Long getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.customerName
     *
     * @param customername the value for item.customerName
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setCustomername(Long customername) {
        this.customername = customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.version
     *
     * @return the value of item.version
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.version
     *
     * @param version the value for item.version
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.remark
     *
     * @return the value of item.remark
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.remark
     *
     * @param remark the value for item.remark
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.available
     *
     * @return the value of item.available
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.available
     *
     * @param available the value for item.available
     *
     * @mbg.generated Wed Mar 13 00:22:05 CST 2019
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}